### ISSUE TITLE
Listings Page - Using the clear button on filters doesn't clear the filters

### ISSUE THREAD

**Issue by Umajin-dev** [gudell/bnymal#12]
Also if people forget the filters on the results will always be filtered. We could quick fix this by resetting the page to clear the filter every time the user reloads the listing page

**Comment by zakwhit** [comment]
David Dupuis said he will help build a custom Button Toggle function that can reset the toggle state.  Might have to push this off to 1.1. If time permits I will try a solution using rectangles over toggles.

**Comment by gudell** [comment]
This is very specific to the status of the toggle on or off of the filter.  As noted on our call yesterday, when you set a filter, press search and then return to the filter page and press clear, the filter button remains in the "filter on" colour, even though the filter is no longer on.  Is this something at require some custom code?

**Comment by gudell** [comment]
To solve this, we have removed the "Clear" button
