### ISSUE TITLE
General Settings Screen - toggle button. Not obvious on its state on or off

### ISSUE THREAD

**Issue by Umajin-dev** [gudell/bnymal#23]

**Comment by gudell** [comment]
i am ok with this in iOS.  Not sure what it looks like in Android.  Can you take screen shots of both states?

**Comment by gudell** [comment]
Should we switch the background colour to green on the toggle?

**Comment by Umajin-dev** [comment]
Is this related to #12? Does it require David Dupuis Toggle Button?

**Comment by Umajin-dev** [comment]
Umajin to make a style change to the toggle slider in the General Setting screen. Green for on and grey for off

**Comment by gudell** [comment]
I have added this element, so marked as closed
