### ISSUE TITLE
Onboarding - Loading Image & Name

### ISSUE THREAD

**Issue by Umajin-dev** [gudell/bnymal#35]
The initial picture is not changing once you have registered.  I think this was suppose to change to the current users dog picture.

**Comment by gudell** [comment]
The name "Bailey" is also showing

**Comment by zakwhit** [comment]
I think we need to just put treat there with now name. We would have to store their profile photo info locally on the device. I have it working but it requires calling the database to grab the photo and it therefore there is loading.

**Comment by gudell** [comment]
Zak, I am good with that, but will reopen for use to address in v1.1

**Comment by zakwhit** [comment]
So do you want me to leave it with the call that grabs the image and name or just put in treat?

**Comment by gudell** [comment]
Just show Treat for now and then we will deal with the calls in the next version
