### ISSUE TITLE
Dog Profile Edit - OSK Pop Up Issues

### ISSUE THREAD

**Issue by gudell** [gudell/bnymal#39]
When filling in the birthdate, the phone pad obscures the entry area

**Comment by zakwhit** [comment]
Recommended for the Umajin team.

**Comment by gudell** [comment]
Seems to be an issue with iOS 10.2

**Comment by Umajin-dev** [comment]
Problem related to text entry on scroll panel, currently in testing for Mobile App 1.1

**Comment by Umajin-dev** [comment]
Testing passed - Confirmed for Mobile App 1.1
