### ISSUE TITLE
Profile Pages - Back Button Navigation Loop

### ISSUE THREAD

**Issue by gudell** [gudell/bnymal#47]
Pressing the back arrow from the main Profile Setting page after loading in data failed by bring me to the Dog Profile Page, but the banner area is on top of the name and breed entry areas.  Pressing the back arrow again bring you to the proper Profile page, but you are now in a loop with the back arrows - this needs to navigate back to the Home Page

**Comment by Umajin-dev** [comment]
I have resolved this.
