### ISSUE TITLE
Onboarding - Account Creation Issue

### ISSUE THREAD

**Issue by gudell** [gudell/bnymal#57]
It appears you can make an account without all the info needed.  All the items in the register form should be required except for Promo Code and there should be an error message that comes up to tell someone what they didn't fill out correctly.

**Comment by gudell** [comment]
According to one tester, "It is possible to register without filling in all fields - however, it is impossible to log into the account. Create an error message if any fields are filled incorrectly"

**Comment by zakwhit** [comment]
Basic validation has been added.
