### ISSUE TITLE
Dog Photo Upload Fail

### ISSUE THREAD

**Issue by glennclarke** [gudell/bnymal#78]
Tested on Samsung Note tab - Wouldn't upload dog photo.

**Comment by gudell** [comment]
This is specific to Android, so may be an issue for Umajin to look into

**Comment by Umajin-dev** [comment]
Hi Glenn; please give us some more details. 

Android version number on your device?
Steps taken i.e. Select from phone or take a photo?
Image details, jpg or png, image size?

**Comment by glennclarke** [comment]
I've asked the tester to provide these details.

**Comment by glennclarke** [comment]
More details from the tester...


Android v6.0.1 on Samsung Galaxy Note Tablet

Steps taken to attempt photo upload 

1) From Home page, clicked profile icon in upper right corner
2) On Profile page, clicked "Edit Dog Profile"
3) On Dog Profile page, clicked "Edit Photo" (overlayed on current photo of dog w/ hat/glasses)
4) 3 options pop up...
- Take a Photo
- Select from Phone (which should probably be "Select from Library" as I'm on a tablet, not a phone 
- Cancel

I clicked "Select from Phone". From my Images library, I tried several photos. As soon as I select one, I'm immediately returned to my Edit Dog Profile page with no change to photo.

Further...I also tested the Take a Photo option this morning. My camera opens, I took new photo, and selected OK. I was presented then with a Please try again pop up box, which was over-laid on the Edit Dog Profile page that did show the new photo. Closed that pop up by selecting OK, which returned me to Edit Dog Profile page. However, when I clicked Save, I was returned to the Dog Profile page without the new photo being saved.

**Comment by glennclarke** [comment]
Image attempted to be uploaded was ~1.3Mb is size.

**Comment by Umajin-dev** [comment]
Select from phone issue related to Android 7 / Nougat issue, fix in progress may or may not be available for Mobile App 1.1, depending on testing result.

**Comment by Umajin-dev** [comment]
Testing Passed - Confirmed for Mobile App 1.1
